# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          mingming
baseurl:        # ""
url:            # "https://mjb940806.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         mingming # Jihye Leee
  url:          # https://jihyeleee.com/
  email:        _mingming@kakao.com  
  github:       mjb940806
  twitter:      # hitchhikerj

# Custom vars
version:        # 3.4.1
github:         #  
  repo:         # https://github.com/iamleejihye/iamleejihye.github.io

exclude:
  - refer/